### ISSUE TITLE
ENV Variables are note interpreted in the autograding "command"

### ISSUE THREAD

**Issue by bricefotzo** [education/autograding-command-grader#18]
Hello !

I'm trying to run tests from a python code that reads env variables. I stored the variables and secrets in Github actions Secrets and Variables but itdoesn't work. 

So I checked and it looks like the `command`input of `classroom-resources/autograding-command-grader@v1`is not reading environement variables.

With this configuration in the classroom.yml to compare `run` and the `command`:

```YAML
    - name: Set up environment
      env:
        VARIABLE: ${{ vars.VARIABLE }}
      run: |
        echo "The VAR is $VARIABLE"
      
    - name: Check variables
      id: check-variables
      uses: classroom-resources/autograding-command-grader@v1
      env :
        VARIABLE: ${{ vars.VARIABLE }}
      with:
        test-name: Check variables
        command: echo "The VAR is $VARIABLE"
        timeout: 10
        max-score: 25
```

The result is :

<img width="505" alt="image" src="https://github.com/user-attachments/assets/315d2509-bc4e-4d49-97ce-0b52506fe5f5">
